# Generated by Django 2.0.2 on 2018-05-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180515_0227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='blog',
            name='photo_credit',
            field=models.TextField(default='ha'),
            preserve_default=False,
        ),
    ]
