# Generated by Django 2.0.2 on 2018-05-19 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180519_2328'),
        ('blog', '0005_auto_20180518_0504'),
    ]

    operations = [
    ]
